# Generated by Selenium IDE
import json
import os
from time import sleep

from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTmp():

    def setup_method(self, method):
        chrome_arg = webdriver.ChromeOptions()
        chrome_arg.debugger_address = '127.0.0.1:8008'
        self.driver = webdriver.Chrome(options=chrome_arg)
        # self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()


    # 登录
    def test_login(self):
        self.driver.get("https://work.weixin.qq.com/")
        self.driver.find_element(By.XPATH, "//*[@class='index_top_operation_loginBtn']").click()
        sleep(16)
        # self.driver.close()


    # 基于缓存实现免登录
    def test_cookie_login(self):
        # todo 可以判断tmp.text是否为空，如果为空就存入cookie如果不为空就不需要调用test_cookie_save（）方法 （还有cookie过期需要重新登录）
        self.test_cookie_save()
        # 读取 cookie
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame#contacts")
        with open("tmp.text", "r", encoding="utf-8") as f:
            # 序列化
            cookies = json.load(f)
        for i in cookies:
            self.driver.add_cookie(i)
        self.driver.refresh()
        sleep(6)

    # 存入 cookie
    def test_cookie_save(self):
        cookies = self.driver.get_cookies()
        with open("tmp.text", "w", encoding="utf-8") as f:
            json.dump(cookies, f)

